/*
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJsonDslScopeProvider extends DelegatingScopeProvider {
}
