/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getFirst <em>First</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getOther <em>Other</em>}</li>
 * </ul>
 *
 * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Object()
 * @model
 * @generated
 */
public interface JSON_Object extends EObject
{
  /**
   * Returns the value of the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' containment reference.
   * @see #setFirst(JSON_Member)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Object_First()
   * @model containment="true"
   * @generated
   */
  JSON_Member getFirst();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getFirst <em>First</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' containment reference.
   * @see #getFirst()
   * @generated
   */
  void setFirst(JSON_Member value);

  /**
   * Returns the value of the '<em><b>Other</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other</em>' containment reference list.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Object_Other()
   * @model containment="true"
   * @generated
   */
  EList<JSON_Member> getOther();

} // JSON_Object
