/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getZahl <em>Zahl</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getKomma <em>Komma</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getExpo <em>Expo</em>}</li>
 * </ul>
 *
 * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Number()
 * @model
 * @generated
 */
public interface JSON_Number extends EObject
{
  /**
   * Returns the value of the '<em><b>Zahl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zahl</em>' attribute.
   * @see #setZahl(int)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Number_Zahl()
   * @model
   * @generated
   */
  int getZahl();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getZahl <em>Zahl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zahl</em>' attribute.
   * @see #getZahl()
   * @generated
   */
  void setZahl(int value);

  /**
   * Returns the value of the '<em><b>Komma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Komma</em>' attribute.
   * @see #setKomma(int)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Number_Komma()
   * @model
   * @generated
   */
  int getKomma();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getKomma <em>Komma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Komma</em>' attribute.
   * @see #getKomma()
   * @generated
   */
  void setKomma(int value);

  /**
   * Returns the value of the '<em><b>Expo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expo</em>' attribute.
   * @see #setExpo(int)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Number_Expo()
   * @model
   * @generated
   */
  int getExpo();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getExpo <em>Expo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expo</em>' attribute.
   * @see #getExpo()
   * @generated
   */
  void setExpo(int value);

} // JSON_Number
