/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String#getJson_string <em>Json string</em>}</li>
 * </ul>
 *
 * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_String()
 * @model
 * @generated
 */
public interface JSON_String extends EObject
{
  /**
   * Returns the value of the '<em><b>Json string</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Json string</em>' attribute.
   * @see #setJson_string(String)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_String_Json_string()
   * @model
   * @generated
   */
  String getJson_string();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String#getJson_string <em>Json string</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Json string</em>' attribute.
   * @see #getJson_string()
   * @generated
   */
  void setJson_string(String value);

} // JSON_String
