/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslFactory
 * @model kind="package"
 * @generated
 */
public interface JsonDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jsonDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/aufgabe4/jsondsl/JsonDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jsonDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonDslPackage eINSTANCE = org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_DocumentImpl <em>JSON Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_DocumentImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Document()
   * @generated
   */
  int JSON_DOCUMENT = 0;

  /**
   * The feature id for the '<em><b>Json value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_DOCUMENT__JSON_VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_DOCUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ValueImpl <em>JSON Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ValueImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Value()
   * @generated
   */
  int JSON_VALUE = 1;

  /**
   * The feature id for the '<em><b>Json value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_VALUE__JSON_VALUE = 0;

  /**
   * The number of structural features of the '<em>JSON Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ArrayImpl <em>JSON Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ArrayImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Array()
   * @generated
   */
  int JSON_ARRAY = 2;

  /**
   * The feature id for the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARRAY__FIRST = 0;

  /**
   * The feature id for the '<em><b>Other</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARRAY__OTHER = 1;

  /**
   * The number of structural features of the '<em>JSON Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_ARRAY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_StringImpl <em>JSON String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_StringImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_String()
   * @generated
   */
  int JSON_STRING = 3;

  /**
   * The feature id for the '<em><b>Json string</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING__JSON_STRING = 0;

  /**
   * The number of structural features of the '<em>JSON String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_BooleanImpl <em>JSON Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_BooleanImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Boolean()
   * @generated
   */
  int JSON_BOOLEAN = 4;

  /**
   * The feature id for the '<em><b>Json boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN__JSON_BOOLEAN = 0;

  /**
   * The number of structural features of the '<em>JSON Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl <em>JSON Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Number()
   * @generated
   */
  int JSON_NUMBER = 5;

  /**
   * The feature id for the '<em><b>Zahl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER__ZAHL = 0;

  /**
   * The feature id for the '<em><b>Komma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER__KOMMA = 1;

  /**
   * The feature id for the '<em><b>Expo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER__EXPO = 2;

  /**
   * The number of structural features of the '<em>JSON Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl <em>JSON Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Member()
   * @generated
   */
  int JSON_MEMBER = 6;

  /**
   * The feature id for the '<em><b>Json member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MEMBER__JSON_MEMBER = 0;

  /**
   * The feature id for the '<em><b>Json value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MEMBER__JSON_VALUE = 1;

  /**
   * The number of structural features of the '<em>JSON Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MEMBER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ObjectImpl <em>JSON Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ObjectImpl
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Object()
   * @generated
   */
  int JSON_OBJECT = 7;

  /**
   * The feature id for the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT__FIRST = 0;

  /**
   * The feature id for the '<em><b>Other</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT__OTHER = 1;

  /**
   * The number of structural features of the '<em>JSON Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_OBJECT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Document <em>JSON Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Document</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Document
   * @generated
   */
  EClass getJSON_Document();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Document#getJson_value <em>Json value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json value</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Document#getJson_value()
   * @see #getJSON_Document()
   * @generated
   */
  EReference getJSON_Document_Json_value();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value <em>JSON Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Value</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value
   * @generated
   */
  EClass getJSON_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value#getJson_value <em>Json value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json value</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value#getJson_value()
   * @see #getJSON_Value()
   * @generated
   */
  EReference getJSON_Value_Json_value();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array <em>JSON Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Array</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array
   * @generated
   */
  EClass getJSON_Array();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array#getFirst()
   * @see #getJSON_Array()
   * @generated
   */
  EReference getJSON_Array_First();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array#getOther <em>Other</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Other</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array#getOther()
   * @see #getJSON_Array()
   * @generated
   */
  EReference getJSON_Array_Other();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String <em>JSON String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON String</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String
   * @generated
   */
  EClass getJSON_String();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String#getJson_string <em>Json string</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Json string</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String#getJson_string()
   * @see #getJSON_String()
   * @generated
   */
  EAttribute getJSON_String_Json_string();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean <em>JSON Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Boolean</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean
   * @generated
   */
  EClass getJSON_Boolean();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean#getJson_boolean <em>Json boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Json boolean</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean#getJson_boolean()
   * @see #getJSON_Boolean()
   * @generated
   */
  EAttribute getJSON_Boolean_Json_boolean();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number <em>JSON Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Number</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number
   * @generated
   */
  EClass getJSON_Number();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getZahl <em>Zahl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Zahl</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getZahl()
   * @see #getJSON_Number()
   * @generated
   */
  EAttribute getJSON_Number_Zahl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getKomma <em>Komma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Komma</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getKomma()
   * @see #getJSON_Number()
   * @generated
   */
  EAttribute getJSON_Number_Komma();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getExpo <em>Expo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expo</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number#getExpo()
   * @see #getJSON_Number()
   * @generated
   */
  EAttribute getJSON_Number_Expo();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member <em>JSON Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Member</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member
   * @generated
   */
  EClass getJSON_Member();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member#getJson_member <em>Json member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json member</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member#getJson_member()
   * @see #getJSON_Member()
   * @generated
   */
  EReference getJSON_Member_Json_member();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member#getJson_value <em>Json value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Json value</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member#getJson_value()
   * @see #getJSON_Member()
   * @generated
   */
  EReference getJSON_Member_Json_value();

  /**
   * Returns the meta object for class '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object <em>JSON Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Object</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object
   * @generated
   */
  EClass getJSON_Object();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getFirst()
   * @see #getJSON_Object()
   * @generated
   */
  EReference getJSON_Object_First();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getOther <em>Other</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Other</em>'.
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object#getOther()
   * @see #getJSON_Object()
   * @generated
   */
  EReference getJSON_Object_Other();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonDslFactory getJsonDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_DocumentImpl <em>JSON Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_DocumentImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Document()
     * @generated
     */
    EClass JSON_DOCUMENT = eINSTANCE.getJSON_Document();

    /**
     * The meta object literal for the '<em><b>Json value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_DOCUMENT__JSON_VALUE = eINSTANCE.getJSON_Document_Json_value();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ValueImpl <em>JSON Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ValueImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Value()
     * @generated
     */
    EClass JSON_VALUE = eINSTANCE.getJSON_Value();

    /**
     * The meta object literal for the '<em><b>Json value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_VALUE__JSON_VALUE = eINSTANCE.getJSON_Value_Json_value();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ArrayImpl <em>JSON Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ArrayImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Array()
     * @generated
     */
    EClass JSON_ARRAY = eINSTANCE.getJSON_Array();

    /**
     * The meta object literal for the '<em><b>First</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_ARRAY__FIRST = eINSTANCE.getJSON_Array_First();

    /**
     * The meta object literal for the '<em><b>Other</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_ARRAY__OTHER = eINSTANCE.getJSON_Array_Other();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_StringImpl <em>JSON String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_StringImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_String()
     * @generated
     */
    EClass JSON_STRING = eINSTANCE.getJSON_String();

    /**
     * The meta object literal for the '<em><b>Json string</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_STRING__JSON_STRING = eINSTANCE.getJSON_String_Json_string();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_BooleanImpl <em>JSON Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_BooleanImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Boolean()
     * @generated
     */
    EClass JSON_BOOLEAN = eINSTANCE.getJSON_Boolean();

    /**
     * The meta object literal for the '<em><b>Json boolean</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_BOOLEAN__JSON_BOOLEAN = eINSTANCE.getJSON_Boolean_Json_boolean();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl <em>JSON Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Number()
     * @generated
     */
    EClass JSON_NUMBER = eINSTANCE.getJSON_Number();

    /**
     * The meta object literal for the '<em><b>Zahl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NUMBER__ZAHL = eINSTANCE.getJSON_Number_Zahl();

    /**
     * The meta object literal for the '<em><b>Komma</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NUMBER__KOMMA = eINSTANCE.getJSON_Number_Komma();

    /**
     * The meta object literal for the '<em><b>Expo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NUMBER__EXPO = eINSTANCE.getJSON_Number_Expo();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl <em>JSON Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Member()
     * @generated
     */
    EClass JSON_MEMBER = eINSTANCE.getJSON_Member();

    /**
     * The meta object literal for the '<em><b>Json member</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_MEMBER__JSON_MEMBER = eINSTANCE.getJSON_Member_Json_member();

    /**
     * The meta object literal for the '<em><b>Json value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_MEMBER__JSON_VALUE = eINSTANCE.getJSON_Member_Json_value();

    /**
     * The meta object literal for the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ObjectImpl <em>JSON Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ObjectImpl
     * @see org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JsonDslPackageImpl#getJSON_Object()
     * @generated
     */
    EClass JSON_OBJECT = eINSTANCE.getJSON_Object();

    /**
     * The meta object literal for the '<em><b>First</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_OBJECT__FIRST = eINSTANCE.getJSON_Object_First();

    /**
     * The meta object literal for the '<em><b>Other</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_OBJECT__OTHER = eINSTANCE.getJSON_Object_Other();

  }

} //JsonDslPackage
