/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean#getJson_boolean <em>Json boolean</em>}</li>
 * </ul>
 *
 * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Boolean()
 * @model
 * @generated
 */
public interface JSON_Boolean extends EObject
{
  /**
   * Returns the value of the '<em><b>Json boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Json boolean</em>' attribute.
   * @see #setJson_boolean(String)
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#getJSON_Boolean_Json_boolean()
   * @model
   * @generated
   */
  String getJson_boolean();

  /**
   * Sets the value of the '{@link org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean#getJson_boolean <em>Json boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Json boolean</em>' attribute.
   * @see #getJson_boolean()
   * @generated
   */
  void setJson_boolean(String value);

} // JSON_Boolean
