/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Array;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Boolean;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Document;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Object;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslFactory;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JsonDslPackageImpl extends EPackageImpl implements JsonDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_DocumentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_ValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_ArrayEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_StringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_BooleanEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_NumberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_MemberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsoN_ObjectEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private JsonDslPackageImpl()
  {
    super(eNS_URI, JsonDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link JsonDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static JsonDslPackage init()
  {
    if (isInited) return (JsonDslPackage)EPackage.Registry.INSTANCE.getEPackage(JsonDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredJsonDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    JsonDslPackageImpl theJsonDslPackage = registeredJsonDslPackage instanceof JsonDslPackageImpl ? (JsonDslPackageImpl)registeredJsonDslPackage : new JsonDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theJsonDslPackage.createPackageContents();

    // Initialize created meta-data
    theJsonDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theJsonDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(JsonDslPackage.eNS_URI, theJsonDslPackage);
    return theJsonDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Document()
  {
    return jsoN_DocumentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Document_Json_value()
  {
    return (EReference)jsoN_DocumentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Value()
  {
    return jsoN_ValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Value_Json_value()
  {
    return (EReference)jsoN_ValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Array()
  {
    return jsoN_ArrayEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Array_First()
  {
    return (EReference)jsoN_ArrayEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Array_Other()
  {
    return (EReference)jsoN_ArrayEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_String()
  {
    return jsoN_StringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJSON_String_Json_string()
  {
    return (EAttribute)jsoN_StringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Boolean()
  {
    return jsoN_BooleanEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJSON_Boolean_Json_boolean()
  {
    return (EAttribute)jsoN_BooleanEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Number()
  {
    return jsoN_NumberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJSON_Number_Zahl()
  {
    return (EAttribute)jsoN_NumberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJSON_Number_Komma()
  {
    return (EAttribute)jsoN_NumberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJSON_Number_Expo()
  {
    return (EAttribute)jsoN_NumberEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Member()
  {
    return jsoN_MemberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Member_Json_member()
  {
    return (EReference)jsoN_MemberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Member_Json_value()
  {
    return (EReference)jsoN_MemberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSON_Object()
  {
    return jsoN_ObjectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Object_First()
  {
    return (EReference)jsoN_ObjectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSON_Object_Other()
  {
    return (EReference)jsoN_ObjectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDslFactory getJsonDslFactory()
  {
    return (JsonDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    jsoN_DocumentEClass = createEClass(JSON_DOCUMENT);
    createEReference(jsoN_DocumentEClass, JSON_DOCUMENT__JSON_VALUE);

    jsoN_ValueEClass = createEClass(JSON_VALUE);
    createEReference(jsoN_ValueEClass, JSON_VALUE__JSON_VALUE);

    jsoN_ArrayEClass = createEClass(JSON_ARRAY);
    createEReference(jsoN_ArrayEClass, JSON_ARRAY__FIRST);
    createEReference(jsoN_ArrayEClass, JSON_ARRAY__OTHER);

    jsoN_StringEClass = createEClass(JSON_STRING);
    createEAttribute(jsoN_StringEClass, JSON_STRING__JSON_STRING);

    jsoN_BooleanEClass = createEClass(JSON_BOOLEAN);
    createEAttribute(jsoN_BooleanEClass, JSON_BOOLEAN__JSON_BOOLEAN);

    jsoN_NumberEClass = createEClass(JSON_NUMBER);
    createEAttribute(jsoN_NumberEClass, JSON_NUMBER__ZAHL);
    createEAttribute(jsoN_NumberEClass, JSON_NUMBER__KOMMA);
    createEAttribute(jsoN_NumberEClass, JSON_NUMBER__EXPO);

    jsoN_MemberEClass = createEClass(JSON_MEMBER);
    createEReference(jsoN_MemberEClass, JSON_MEMBER__JSON_MEMBER);
    createEReference(jsoN_MemberEClass, JSON_MEMBER__JSON_VALUE);

    jsoN_ObjectEClass = createEClass(JSON_OBJECT);
    createEReference(jsoN_ObjectEClass, JSON_OBJECT__FIRST);
    createEReference(jsoN_ObjectEClass, JSON_OBJECT__OTHER);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(jsoN_DocumentEClass, JSON_Document.class, "JSON_Document", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSON_Document_Json_value(), this.getJSON_Value(), null, "json_value", null, 0, 1, JSON_Document.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_ValueEClass, JSON_Value.class, "JSON_Value", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSON_Value_Json_value(), ecorePackage.getEObject(), null, "json_value", null, 0, 1, JSON_Value.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_ArrayEClass, JSON_Array.class, "JSON_Array", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSON_Array_First(), this.getJSON_Value(), null, "first", null, 0, 1, JSON_Array.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJSON_Array_Other(), this.getJSON_Value(), null, "other", null, 0, -1, JSON_Array.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_StringEClass, JSON_String.class, "JSON_String", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJSON_String_Json_string(), ecorePackage.getEString(), "json_string", null, 0, 1, JSON_String.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_BooleanEClass, JSON_Boolean.class, "JSON_Boolean", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJSON_Boolean_Json_boolean(), ecorePackage.getEString(), "json_boolean", null, 0, 1, JSON_Boolean.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_NumberEClass, JSON_Number.class, "JSON_Number", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJSON_Number_Zahl(), ecorePackage.getEInt(), "zahl", null, 0, 1, JSON_Number.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJSON_Number_Komma(), ecorePackage.getEInt(), "komma", null, 0, 1, JSON_Number.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJSON_Number_Expo(), ecorePackage.getEInt(), "expo", null, 0, 1, JSON_Number.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_MemberEClass, JSON_Member.class, "JSON_Member", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSON_Member_Json_member(), this.getJSON_String(), null, "json_member", null, 0, 1, JSON_Member.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJSON_Member_Json_value(), this.getJSON_Value(), null, "json_value", null, 0, 1, JSON_Member.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jsoN_ObjectEClass, JSON_Object.class, "JSON_Object", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSON_Object_First(), this.getJSON_Member(), null, "first", null, 0, 1, JSON_Object.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJSON_Object_Other(), this.getJSON_Member(), null, "other", null, 0, -1, JSON_Object.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //JsonDslPackageImpl
