/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Number;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>JSON Number</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl#getZahl <em>Zahl</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl#getKomma <em>Komma</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_NumberImpl#getExpo <em>Expo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JSON_NumberImpl extends MinimalEObjectImpl.Container implements JSON_Number
{
  /**
   * The default value of the '{@link #getZahl() <em>Zahl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZahl()
   * @generated
   * @ordered
   */
  protected static final int ZAHL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getZahl() <em>Zahl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZahl()
   * @generated
   * @ordered
   */
  protected int zahl = ZAHL_EDEFAULT;

  /**
   * The default value of the '{@link #getKomma() <em>Komma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKomma()
   * @generated
   * @ordered
   */
  protected static final int KOMMA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getKomma() <em>Komma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKomma()
   * @generated
   * @ordered
   */
  protected int komma = KOMMA_EDEFAULT;

  /**
   * The default value of the '{@link #getExpo() <em>Expo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpo()
   * @generated
   * @ordered
   */
  protected static final int EXPO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getExpo() <em>Expo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpo()
   * @generated
   * @ordered
   */
  protected int expo = EXPO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JSON_NumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.JSON_NUMBER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getZahl()
  {
    return zahl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZahl(int newZahl)
  {
    int oldZahl = zahl;
    zahl = newZahl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_NUMBER__ZAHL, oldZahl, zahl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getKomma()
  {
    return komma;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKomma(int newKomma)
  {
    int oldKomma = komma;
    komma = newKomma;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_NUMBER__KOMMA, oldKomma, komma));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getExpo()
  {
    return expo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpo(int newExpo)
  {
    int oldExpo = expo;
    expo = newExpo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_NUMBER__EXPO, oldExpo, expo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_NUMBER__ZAHL:
        return getZahl();
      case JsonDslPackage.JSON_NUMBER__KOMMA:
        return getKomma();
      case JsonDslPackage.JSON_NUMBER__EXPO:
        return getExpo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_NUMBER__ZAHL:
        setZahl((Integer)newValue);
        return;
      case JsonDslPackage.JSON_NUMBER__KOMMA:
        setKomma((Integer)newValue);
        return;
      case JsonDslPackage.JSON_NUMBER__EXPO:
        setExpo((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_NUMBER__ZAHL:
        setZahl(ZAHL_EDEFAULT);
        return;
      case JsonDslPackage.JSON_NUMBER__KOMMA:
        setKomma(KOMMA_EDEFAULT);
        return;
      case JsonDslPackage.JSON_NUMBER__EXPO:
        setExpo(EXPO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_NUMBER__ZAHL:
        return zahl != ZAHL_EDEFAULT;
      case JsonDslPackage.JSON_NUMBER__KOMMA:
        return komma != KOMMA_EDEFAULT;
      case JsonDslPackage.JSON_NUMBER__EXPO:
        return expo != EXPO_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (zahl: ");
    result.append(zahl);
    result.append(", komma: ");
    result.append(komma);
    result.append(", expo: ");
    result.append(expo);
    result.append(')');
    return result.toString();
  }

} //JSON_NumberImpl
