/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>JSON Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_ValueImpl#getJson_value <em>Json value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JSON_ValueImpl extends MinimalEObjectImpl.Container implements JSON_Value
{
  /**
   * The cached value of the '{@link #getJson_value() <em>Json value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJson_value()
   * @generated
   * @ordered
   */
  protected EObject json_value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JSON_ValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.JSON_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getJson_value()
  {
    return json_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJson_value(EObject newJson_value, NotificationChain msgs)
  {
    EObject oldJson_value = json_value;
    json_value = newJson_value;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_VALUE__JSON_VALUE, oldJson_value, newJson_value);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJson_value(EObject newJson_value)
  {
    if (newJson_value != json_value)
    {
      NotificationChain msgs = null;
      if (json_value != null)
        msgs = ((InternalEObject)json_value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_VALUE__JSON_VALUE, null, msgs);
      if (newJson_value != null)
        msgs = ((InternalEObject)newJson_value).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_VALUE__JSON_VALUE, null, msgs);
      msgs = basicSetJson_value(newJson_value, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_VALUE__JSON_VALUE, newJson_value, newJson_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_VALUE__JSON_VALUE:
        return basicSetJson_value(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_VALUE__JSON_VALUE:
        return getJson_value();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_VALUE__JSON_VALUE:
        setJson_value((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_VALUE__JSON_VALUE:
        setJson_value((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_VALUE__JSON_VALUE:
        return json_value != null;
    }
    return super.eIsSet(featureID);
  }

} //JSON_ValueImpl
