/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.aufgabe4.jsondsl.jsonDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JsonDslFactoryImpl extends EFactoryImpl implements JsonDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static JsonDslFactory init()
  {
    try
    {
      JsonDslFactory theJsonDslFactory = (JsonDslFactory)EPackage.Registry.INSTANCE.getEFactory(JsonDslPackage.eNS_URI);
      if (theJsonDslFactory != null)
      {
        return theJsonDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new JsonDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JsonDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case JsonDslPackage.JSON_DOCUMENT: return createJSON_Document();
      case JsonDslPackage.JSON_VALUE: return createJSON_Value();
      case JsonDslPackage.JSON_ARRAY: return createJSON_Array();
      case JsonDslPackage.JSON_STRING: return createJSON_String();
      case JsonDslPackage.JSON_BOOLEAN: return createJSON_Boolean();
      case JsonDslPackage.JSON_NUMBER: return createJSON_Number();
      case JsonDslPackage.JSON_MEMBER: return createJSON_Member();
      case JsonDslPackage.JSON_OBJECT: return createJSON_Object();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Document createJSON_Document()
  {
    JSON_DocumentImpl jsoN_Document = new JSON_DocumentImpl();
    return jsoN_Document;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Value createJSON_Value()
  {
    JSON_ValueImpl jsoN_Value = new JSON_ValueImpl();
    return jsoN_Value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Array createJSON_Array()
  {
    JSON_ArrayImpl jsoN_Array = new JSON_ArrayImpl();
    return jsoN_Array;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_String createJSON_String()
  {
    JSON_StringImpl jsoN_String = new JSON_StringImpl();
    return jsoN_String;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Boolean createJSON_Boolean()
  {
    JSON_BooleanImpl jsoN_Boolean = new JSON_BooleanImpl();
    return jsoN_Boolean;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Number createJSON_Number()
  {
    JSON_NumberImpl jsoN_Number = new JSON_NumberImpl();
    return jsoN_Number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Member createJSON_Member()
  {
    JSON_MemberImpl jsoN_Member = new JSON_MemberImpl();
    return jsoN_Member;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Object createJSON_Object()
  {
    JSON_ObjectImpl jsoN_Object = new JSON_ObjectImpl();
    return jsoN_Object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonDslPackage getJsonDslPackage()
  {
    return (JsonDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static JsonDslPackage getPackage()
  {
    return JsonDslPackage.eINSTANCE;
  }

} //JsonDslFactoryImpl
