/**
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.jsonDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Member;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_String;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JSON_Value;
import org.xtext.aufgabe4.jsondsl.jsonDsl.JsonDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>JSON Member</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl#getJson_member <em>Json member</em>}</li>
 *   <li>{@link org.xtext.aufgabe4.jsondsl.jsonDsl.impl.JSON_MemberImpl#getJson_value <em>Json value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JSON_MemberImpl extends MinimalEObjectImpl.Container implements JSON_Member
{
  /**
   * The cached value of the '{@link #getJson_member() <em>Json member</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJson_member()
   * @generated
   * @ordered
   */
  protected JSON_String json_member;

  /**
   * The cached value of the '{@link #getJson_value() <em>Json value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJson_value()
   * @generated
   * @ordered
   */
  protected JSON_Value json_value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JSON_MemberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonDslPackage.Literals.JSON_MEMBER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_String getJson_member()
  {
    return json_member;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJson_member(JSON_String newJson_member, NotificationChain msgs)
  {
    JSON_String oldJson_member = json_member;
    json_member = newJson_member;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_MEMBER__JSON_MEMBER, oldJson_member, newJson_member);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJson_member(JSON_String newJson_member)
  {
    if (newJson_member != json_member)
    {
      NotificationChain msgs = null;
      if (json_member != null)
        msgs = ((InternalEObject)json_member).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_MEMBER__JSON_MEMBER, null, msgs);
      if (newJson_member != null)
        msgs = ((InternalEObject)newJson_member).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_MEMBER__JSON_MEMBER, null, msgs);
      msgs = basicSetJson_member(newJson_member, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_MEMBER__JSON_MEMBER, newJson_member, newJson_member));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JSON_Value getJson_value()
  {
    return json_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJson_value(JSON_Value newJson_value, NotificationChain msgs)
  {
    JSON_Value oldJson_value = json_value;
    json_value = newJson_value;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_MEMBER__JSON_VALUE, oldJson_value, newJson_value);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJson_value(JSON_Value newJson_value)
  {
    if (newJson_value != json_value)
    {
      NotificationChain msgs = null;
      if (json_value != null)
        msgs = ((InternalEObject)json_value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_MEMBER__JSON_VALUE, null, msgs);
      if (newJson_value != null)
        msgs = ((InternalEObject)newJson_value).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonDslPackage.JSON_MEMBER__JSON_VALUE, null, msgs);
      msgs = basicSetJson_value(newJson_value, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonDslPackage.JSON_MEMBER__JSON_VALUE, newJson_value, newJson_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_MEMBER__JSON_MEMBER:
        return basicSetJson_member(null, msgs);
      case JsonDslPackage.JSON_MEMBER__JSON_VALUE:
        return basicSetJson_value(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_MEMBER__JSON_MEMBER:
        return getJson_member();
      case JsonDslPackage.JSON_MEMBER__JSON_VALUE:
        return getJson_value();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_MEMBER__JSON_MEMBER:
        setJson_member((JSON_String)newValue);
        return;
      case JsonDslPackage.JSON_MEMBER__JSON_VALUE:
        setJson_value((JSON_Value)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_MEMBER__JSON_MEMBER:
        setJson_member((JSON_String)null);
        return;
      case JsonDslPackage.JSON_MEMBER__JSON_VALUE:
        setJson_value((JSON_Value)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonDslPackage.JSON_MEMBER__JSON_MEMBER:
        return json_member != null;
      case JsonDslPackage.JSON_MEMBER__JSON_VALUE:
        return json_value != null;
    }
    return super.eIsSet(featureID);
  }

} //JSON_MemberImpl
