/*
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonDslRuntimeModule extends AbstractJsonDslRuntimeModule {
}
