package Petrinetz.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptMarke = createDescriptorForMarke();
  /*package*/ final ConceptDescriptor myConceptPetrinetz = createDescriptorForPetrinetz();
  /*package*/ final ConceptDescriptor myConceptStelle = createDescriptorForStelle();
  /*package*/ final ConceptDescriptor myConceptStellenReference = createDescriptorForStellenReference();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptMarke, myConceptPetrinetz, myConceptStelle, myConceptStellenReference, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Marke:
        return myConceptMarke;
      case LanguageConceptSwitch.Petrinetz:
        return myConceptPetrinetz;
      case LanguageConceptSwitch.Stelle:
        return myConceptStelle;
      case LanguageConceptSwitch.StellenReference:
        return myConceptStellenReference;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForMarke() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Petrinetz", "Marke", 0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921bL);
    b.class_(false, false, false);
    b.origin("r:2823fc59-4fda-4dc8-9c31-04a97812e045(Petrinetz.structure)/6698377177723539995");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPetrinetz() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Petrinetz", "Petrinetz", 0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9216L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2823fc59-4fda-4dc8-9c31-04a97812e045(Petrinetz.structure)/6698377177723539990");
    b.version(2);
    b.aggregate("stellen", 0x5cf56a8db9cb921dL).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9219L).optional(true).ordered(true).multiple(true).origin("6698377177723539997").done();
    b.aggregate("transitionen", 0x5cf56a8db9cb921eL).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921aL).optional(true).ordered(true).multiple(true).origin("6698377177723539998").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStelle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Petrinetz", "Stelle", 0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9219L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2823fc59-4fda-4dc8-9c31-04a97812e045(Petrinetz.structure)/6698377177723539993");
    b.version(2);
    b.aggregate("marken", 0x5cf56a8db9cb9220L).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921bL).optional(true).ordered(true).multiple(true).origin("6698377177723540000").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStellenReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Petrinetz", "StellenReference", 0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9222L);
    b.class_(false, false, false);
    b.origin("r:2823fc59-4fda-4dc8-9c31-04a97812e045(Petrinetz.structure)/6698377177723540002");
    b.version(2);
    b.associate("stelle", 0x5cf56a8db9cb9223L).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9219L).optional(false).origin("6698377177723540003").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Petrinetz", "Transition", 0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2823fc59-4fda-4dc8-9c31-04a97812e045(Petrinetz.structure)/6698377177723539994");
    b.version(2);
    b.aggregate("input", 0x5cf56a8db9cb9224L).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9222L).optional(true).ordered(true).multiple(true).origin("6698377177723540004").done();
    b.aggregate("output", 0x5cf56a8db9cb9225L).target(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9222L).optional(true).ordered(true).multiple(true).origin("6698377177723540005").done();
    return b.create();
  }
}
