/*
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.aufgabe4.jsondsl.ui.internal.JsondslActivator;

public class JsonDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JsondslActivator.getInstance().getInjector("org.xtext.aufgabe4.jsondsl.JsonDsl");
	}

}
