/*
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.aufgabe4.jsondsl.JsonDslRuntimeModule;
import org.xtext.aufgabe4.jsondsl.JsonDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonDslIdeSetup extends JsonDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonDslRuntimeModule(), new JsonDslIdeModule()));
	}
	
}
