/*
 * generated by Xtext 2.25.0
 */
package org.xtext.aufgabe4.jsondsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.aufgabe4.jsondsl.parser.antlr.internal.InternalJsonDslParser;
import org.xtext.aufgabe4.jsondsl.services.JsonDslGrammarAccess;

public class JsonDslParser extends AbstractAntlrParser {

	@Inject
	private JsonDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonDslParser createParser(XtextTokenStream stream) {
		return new InternalJsonDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JSON_Document";
	}

	public JsonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
