package Petrinetz.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Marke_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Petrinetz_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Stelle_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new StellenReference_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Transition_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new StellenReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921bL), MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9216L), MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9219L), MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9222L), MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb921aL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x8151472b9fd84208L, 0xa479dc05429f091aL, 0x5cf56a8db9cb9222L)).seal();
}
